server:
  port: 8080

spring:
  application:
    name: gym-crm-prod
  profiles:
    active: dev

  datasource:
    username: sa
    password: s3cr3t
    url: jdbc:postgresql://localhost:5432/gymcrm
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      data-locations: classpath:data.sql

logging:
  level:
    root: WARN
    com.epam.gymcrm: INFO

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
