server:
  port: 8080

spring:
  application:
    name: gym-crm-prod
  profiles:
    active: dev

  datasource:
    username: sa
    password: s3cr3t
    url: jdbc:postgresql://localhost:5432/gymcrm
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      data-locations: classpath:data.sql

security:
  bruteforce:
    max-attempts: 3
    block-minutes: 5

  jwt:
    secret: ${JWT_SECRET:'this-is-a-very-long-32+chars-secret-key!!'}
    issuer: gym-crm
    access-token-minutes: 30

  cors:
    allowed-origins: "https://app.gym-crm.com"

logging:
  level:
    root: WARN
    com.epam.gymcrm: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: when_authorized
  prometheus:
    metrics:
      export:
        enabled: true
