server:
  port: 8081

spring:
  application:
    name: gym-crm-dev

  datasource:
    url: jdbc:postgresql://localhost:5433/gymcrm_dev
    username: dev_sa
    password: dev_s3cr3t
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      data-locations: classpath:data-dev.sql

logging:
  level:
    root: INFO
    com.epam.gymcrm: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
